"""
Generates roblox_api.luau (enums with values, class hierarchy, member kinds and property types)
from Roblox's API dump, as mirrored by MaximumADHD/Roblox-Client-Tracker.

Run once: python gen_roblox.py [path/to/Full-API-Dump.json]
"""
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
URL = "https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/Full-API-Dump.json"


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            dump = json.load(f)
    else:
        with urllib.request.urlopen(URL) as r:
            dump = json.loads(r.read().decode("utf-8"))

    enums = []
    for e in dump["Enums"]:
        items = ",".join("%s=%d" % (i["Name"], i["Value"]) for i in e["Items"])
        enums.append("%s:%s" % (e["Name"], items))

    classes = []
    for c in dump["Classes"]:
        kinds = {"Function": [], "Event": [], "Property": [], "Callback": []}
        for m in c.get("Members", []):
            # names like "Mass (deprecated)" are not reachable from Lua syntax
            if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", m["Name"]):
                name = m["Name"]
                if m["MemberType"] == "Property":
                    # keep the value type (float, bool, Vector3, ...) for typed stand-ins
                    vt = (m.get("ValueType") or {}).get("Name", "")
                    if re.match(r"^[A-Za-z0-9_]+$", vt):
                        name += ":" + vt
                kinds.setdefault(m["MemberType"], []).append(name)
        classes.append("%s<%s|%s|%s|%s" % (
            c["Name"], c.get("Superclass", "") if c.get("Superclass") != "<<<ROOT>>>" else "",
            ",".join(kinds["Function"]), ",".join(kinds["Event"]), ",".join(kinds["Property"] + kinds["Callback"])))

    out = os.path.join(HERE, "roblox_api.luau")
    with open(out, "w", encoding="ascii", errors="ignore", newline="\n") as f:
        f.write("-- generated by gen_roblox.py from the Roblox API dump (%s)\n" % dump.get("Version"))
        f.write("return {\n")
        f.write('\tenums = "%s",\n' % ";".join(enums))
        f.write('\tclasses = "%s",\n' % ";".join(classes))
        f.write("}\n")
    print("enums %d classes %d -> %s (%d bytes)" % (len(enums), len(classes), out, os.path.getsize(out)))


if __name__ == "__main__":
    main()
