"""
Generates unicode_data.luau: the canonical decomposition, combining class and
composition tables that the runtime's utf8.nfcnormalize / utf8.nfdnormalize
need (Roblox has these functions; the standalone Luau runtime does not).

Run once: python gen_unicode.py
"""
import os
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
HANGUL = range(0xAC00, 0xD7A4)


def main():
    decomp = {}
    ccc = {}
    pairs = {}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF or cp in HANGUL:
            continue
        ch = chr(cp)
        c = unicodedata.combining(ch)
        if c:
            ccc[cp] = c
        d = unicodedata.normalize("NFD", ch)
        if d != ch:
            decomp[cp] = [ord(x) for x in d]
        raw = unicodedata.decomposition(ch)
        if raw and not raw.startswith("<"):
            parts = [int(x, 16) for x in raw.split()]
            if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == ch:
                pairs[(parts[0], parts[1])] = cp

    def enc(n):
        return "%x" % n

    dec_s = ";".join(enc(k) + ":" + ",".join(enc(x) for x in v) for k, v in sorted(decomp.items()))
    ccc_s = ";".join(enc(k) + ":" + enc(v) for k, v in sorted(ccc.items()))
    comp_s = ";".join(enc(a) + "," + enc(b) + ":" + enc(c) for (a, b), c in sorted(pairs.items()))
    with open(os.path.join(HERE, "unicode_data.luau"), "w", encoding="ascii", newline="\n") as f:
        f.write("-- generated by gen_unicode.py from Python's unicodedata %s\n" % unicodedata.unidata_version)
        f.write("return {\n")
        f.write('\tdecomp = "%s",\n' % dec_s)
        f.write('\tccc = "%s",\n' % ccc_s)
        f.write('\tcomp = "%s",\n' % comp_s)
        f.write("}\n")
    print("decomp %d ccc %d comp %d" % (len(decomp), len(ccc), len(pairs)))


if __name__ == "__main__":
    main()
